---
:text:
  :lenny: "( ═í┬░ ═£╩û ═í┬░)"
  :shrug: "┬»\\_(Òâä)_/┬»"
  :support: |-
    ÔÜÖ **Need help?**
    You can join the support server here:
    **https://discord.gg/43SaDy6 **
  :facedesk: https://giphy.com/gifs/XLOsdacfjL5cI
  :smea: https://giphy.com/gifs/Sb2NkTl1oV6eI
:image:
  :soon: images/soon.png
