##~~~ DO NOT OPEN THIS FILE IN NOTEPAD (Use a modern text editor such as Notepad++ or any Unix-based one)  ~~~##
##~~~ If everything displays on one line, do not save the file and instead open in a different editor.      ~~~##
#######################################################################################################
## To get started, please create a bot account at https://discordapp.com/developers/applications/me  ##
## Then create a bot user, find the token and client id, and put them below.                         ##
## It is also highly recommended that you add your user ID to "owners" array. (Lines 71-77)          ##
## Anything after a hash (#) is a comment and will be ignored.                                       ##
#######################################################################################################
## When you're done, save this file as `config.yml` (In the config folder)                           ##
#######################################################################################################

token: Mjk1OTUwMjg3MDcwNTYwMjU2.C7rIsw.az_gJtwJtz-Hv8e_jmq5tQK0WQw # Get from https://discordapp.com/developers/applications/me
client_id: 295950287070560256 # Also get from https://discordapp.com/developers/applications/me
prefixes:
  - "s!"
  - "&"
  - "s!!"

# Set to false for less console output.
verbose: true

# Change the amount of chat logs displayed.
# Can be 'none', 'all' or 'commands'
loglevel: commands

## Set to a custom emoji using <:name:ID>
emoji_tickbox: ✅
emoji_error: ❌
emoji_warning: ⚠
emoji_clear: 🚮
emoji_success: 👌

# Set to "online", "idle", "dnd" or "invisible"
status: idle
game: Powered by Ruby!

 # Change to false if you don't like the bot "typing" all the time.
typing_default: true

# Change to false if private.
show_invite: true
# Best to leave nil unless sure. (Defaults t o a generated URL)
invite_url: nil

# plz dont set to false, closed source is baaad :(
show_source: true
# Change if using your own fork.
source_url: https://github.com/Seriell/Yuuki-Bot

# Will disable the `help` command.
show_help: true
# Change if using your own fork or hosting your own help.
help_url: https://github.com/Seriell/Yuuki-Bot/wiki/Commands

show_support: true
# Change to your server if using your own modified code.
support_server: https://discord.gg/43SaDy6

show_donate_urls: true
# Wrap in <> if using more than one (To avoid huge embeds).
donate_urls:
  # It would be nice if you kept the original devs, but is not required.
  - <https://paypal.me/Seriel>
  - <https://paypal.me/spotlightisok>
# - <https://paypal.me/your_name_here>

##~~~ !! Any user on this list will have full access to the machine the bot is hosted on via eval and bash commands !! ~~~##
##~~~~ Give this power WITH CAUTION ~~~~###
owners:
  - 228574821590499328 # Not a real ID, put yours.
# - 228574821590499328

# To get your user ID: (two methods)
# 1. Enable Developer mode in the client, then right click your name and select "Copy ID"
# 2. Run the bot temporarily and use the info command.

# More features but may break. Set to true to use. If unsure leave as false.
extra_commands: false

##~~~ (: DONT TOUCH THIS PART :) ~~~##

# Init options, if unsure please leave alone to avoid accidental catastrophes.
parse_self: true
parse_bots: false
selfbot: false # Doesn't work on bot accounts.
prefix_type: always
type: :bot